version: '3.8'
name: debate-zone-micro-service

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: examplepassword
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    ports:
      - "8081:8081"

volumes:
  mongodb_data:
